name: cat_breeds_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  html: ^0.15.4
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ic_launcher.png

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/ic_launcher.png
  color: "#FFFFFF"
  android_12:
    image: assets/ic_launcher.png
    color: "#FFFFFF"

  

